export const products = [
  {
    id: 1,
    image: "/images/tees.png",
    hoverImage: "/images/img_1.png",
    image2: "/images/img_1.png",
    title: "Classic Logo Tee",
    price: "€89",
    category: "tees",
    link: "/shop/1",
    description: "A premium heavyweight organic cotton tee featuring our signature classic logo chest print. Relaxed fit, breathable, and built to last.",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: 2,
    image: "/images/img_3.png",
    hoverImage: "/images/img_5.png",
    image2: "/images/img_5.png",
    title: "Linen Blend Shorts",
    price: "€75",
    category: "bottoms-wears",
    link: "/shop/2",
    description: "Relaxed linen blend shorts with an elasticated waistband and adjustable drawcord. Designed for style and comfort in warm weather.",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: 3,
    image: "/images/hoddies.png",
    hoverImage: "/images/img_3.png",
    image2: "/images/img_3.png",
    title: "Oversized Hoodie",
    price: "€110",
    category: "hoodies",
    link: "/shop/3",
    description: "An oversized fit hoodie made from thick loopback cotton fleece. Features a double-layered hood and drop shoulders.",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: 4,
    image: "/images/img_1.png",
    hoverImage: "/images/img_2.png",
    image2: "/images/img_2.png",
    title: "Relaxed Cargo Trousers",
    price: "€110",
    category: "bottoms-wears",
    link: "/shop/4",
    description: "Wide-leg cargo trousers with a relaxed silhouette. Features multiple utility pockets and a drawstring waist.",
    sizes: ["28", "30", "32", "34", "36"],
  },
  {
    id: 5,
    image: "/images/cap.png",
    hoverImage: "/images/headwear.png",
    image2: "/images/headwear.png",
    title: "Minimalist Cap",
    price: "€35",
    category: "headwear",
    link: "/shop/5",
    description: "A clean, unstructured cap with a curved brim. One size fits all with an adjustable back strap.",
    sizes: ["One Size"],
  },
  {
    id: 6,
    image: "/images/img_2.png",
    hoverImage: "/images/img_3.png",
    image2: "/images/img_3.png",
    title: "Denim Tiered Dress",
    price: "€145",
    category: "new-arrival",
    link: "/shop/6",
    description: "A tiered denim dress with a flattering A-line silhouette. Made from sustainable denim with a soft, worn-in feel.",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
]
